/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './*.html',
    './src/**/*.{js,css}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant':         '#b9cacb',
        'on-tertiary-fixed':          '#1e0061',
        'error':                      '#ffb4ab',
        'on-primary-fixed-variant':   '#004f54',
        'tertiary':                   '#faf4ff',
        'on-primary-fixed':           '#002022',
        'on-error':                   '#690005',
        'primary':                    '#dbfcff',
        'surface-container-highest':  '#2d3449',
        'on-secondary-container':     '#00723f',
        'inverse-primary':            '#006970',
        'inverse-on-surface':         '#283044',
        'surface-bright':             '#31394d',
        'on-secondary-fixed':         '#00210e',
        'on-secondary':               '#00391d',
        'surface-container-lowest':   '#060e20',
        'on-primary':                 '#00363a',
        'on-error-container':         '#ffdad6',
        'error-container':            '#93000a',
        'inverse-surface':            '#dae2fd',
        'surface':                    '#0b1326',
        'surface-tint':               '#00dbe9',
        'on-background':              '#dae2fd',
        'surface-container':          '#171f33',
        'outline-variant':            '#3b494b',
        'on-surface':                 '#dae2fd',
        'surface-container-low':      '#131b2e',
        'surface-container-high':     '#222a3d',
        'secondary':                  '#f5fff3',
        'primary-fixed':              '#7df4ff',
        'secondary-fixed':            '#5bffa1',
        'surface-variant':            '#2d3449',
        'primary-fixed-dim':          '#00dbe9',
        'tertiary-fixed-dim':         '#cbbeff',
        'on-tertiary-fixed-variant':  '#4b0fcd',
        'on-primary-container':       '#006970',
        'surface-dim':                '#0b1326',
        'outline':                    '#849495',
        'tertiary-container':         '#ded4ff',
        'on-tertiary-container':      '#643ae5',
        'on-secondary-fixed-variant': '#00522c',
        'primary-container':          '#00f0ff',
        'tertiary-fixed':             '#e7deff',
        'on-tertiary':                '#330098',
        'secondary-fixed-dim':        '#00e383',
        'secondary-container':        '#27ff97',
        'background':                 '#0b1326',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'base':           '8px',
        'container-max':  '1280px',
        'margin-mobile':  '20px',
        'margin-desktop': '64px',
        'gutter':         '24px',
      },
      fontFamily: {
        'headline-lg':        ['Inter', 'sans-serif'],
        'headline-xl':        ['Inter', 'sans-serif'],
        'headline-md':        ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg':            ['Inter', 'sans-serif'],
        'body-md':            ['Inter', 'sans-serif'],
        'label-caps':         ['JetBrains Mono', 'monospace'],
        'code-sm':            ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-xl':      ['64px', { lineHeight: '1.1',  letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg':      ['40px', { lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile':['32px',{ lineHeight: '1.2',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':      ['24px', { lineHeight: '1.4',                            fontWeight: '600' }],
        'body-lg':          ['18px', { lineHeight: '1.6',                            fontWeight: '400' }],
        'body-md':          ['16px', { lineHeight: '1.6',                            fontWeight: '400' }],
        'label-caps':       ['12px', { lineHeight: '1.0',  letterSpacing: '0.1em',   fontWeight: '600' }],
        'code-sm':          ['14px', { lineHeight: '1.5',                            fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
